apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: voting
        image: voting-app
        imagePullPolicy: Never  # Use local image only
        ports:
        - containerPort: 3000  # Fix port to match app.js
        env:
        - name: REDIS_HOST
          value: "redis-service"
---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
spec:
  selector:
    app: voting
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
